# sheet names
SHEET_CONFIGURATION = "Assay Configuration"
SHEET_LOG = "Operation Log"
SHEET_RATE = "Rate"
SHEET_RAW = "Raw"
SHEET_CALIBRATION = "Calibration"
SHEET_RATE_PLATES = "Rate (Plates)"
SHEET_RATE_COLUMNS = "Rate (Columns)"
SHEET_NORMALIZED_RATE = "Normalized Rate"
SHEET_NORMALIZED_RATE_PLATES = "Normalized Rate (Plates)"
SHEET_NORMALIZED_RATE_COLUMNS = "Normalized Rate (Columns)"
SHEET_BASELINED_RATE = "Baselined Rate"
SHEET_BASELINED_RATE_PLATES = "Baselined Rate (Plates)"
SHEET_BASELINED_RATE_COLUMNS = "Baselined Rate (Columns)"

# command names used in calibration log
CMD_CALIBRATE = "Calibrate"
CMD_COARSE_CALIBRATE = "CoarseCalibrate"
CMD_EQUILIBRATE = "Equilibrate"
CMD_FINE_CALIBRATE = "FineCalibrate"
CMD_HOME = "Home"
CMD_INJECT = "Inject"
CMD_LOAD_PLATE = "LoadPlate"
CMD_LOAD_PROBES = "LoadProbes"
CMD_MEASURE = "Measure"
CMD_MIX = "Mix"
CMD_OFFSET_CALIBRATE = "OffsetCalibrate"
CMD_PRE_CALIBRATE = "PreCalibrate"
CMD_UNLOAD_CARTRIDGE = "UnloadCartridge"
CMD_WAIT = "Wait"
