# sheet names
CONFIGURATION = "Assay Configuration"
LOG = "Operation Log"
RATE = "Rate"
RAW = "Raw"
CALIBRATION = "Calibration"
RATE_PLATES = "Rate (Plates)"
RATE_COLUMNS = "Rate (Columns)"
NORMALIZED_RATE = "Normalized Rate"
NORMALIZED_RATE_PLATES = "Normalized Rate (Plates)"
NORMALIZED_RATE_COLUMNS = "Normalized Rate (Columns)"
BASELINED_RATE = "Baselined Rate"
BASELINED_RATE_PLATES = "Baselined Rate (Plates)"
BASELINED_RATE_COLUMNS = "Baselined Rate (Columns)"
