# sheet names
CONFIGURATION = "Assay Configuration"
LOG = "Operation Log"
RATE = "Rate"
RAW = "Raw"
CALIBRATION = "Calibration"
RATE_PLATES = "Rate (Plates)"
RATE_COLUMNS = "Rate (Columns)"
NORMALIZED_RATE = "Normalized Rate"
NORMALIZED_RATE_PLATES = "Normalized Rate (Plates)"
NORMALIZED_RATE_COLUMNS = "Normalized Rate (Columns)"
BASELINED_RATE = "Baselined Rate"
BASELINED_RATE_PLATES = "Baselined Rate (Plates)"
BASELINED_RATE_COLUMNS = "Baselined Rate (Columns)"

# command names used in calibration log
CMD_CALIBRATE = "Calibrate"
CMD_COARSE_CALIBRATE = "CoarseCalibrate"
CMD_EQUILIBRATE = "Equilibrate"
CMD_FINE_CALIBRATE = "FineCalibrate"
CMD_HOME = "Home"
CMD_INJECT = "Inject"
CMD_LOAD_PLATE = "LoadPlate"
CMD_LOAD_PROBES = "LoadProbes"
CMD_MEASURE = "Measure"
CMD_MIX = "Mix"
CMD_OFFSET_CALIBRATE = "OffsetCalibrate"
CMD_PRE_CALIBRATE = "PreCalibrate"
CMD_UNLOAD_CARTRIDGE = "UnloadCartridge"
CMD_WAIT = "Wait"
